name: CD

on:
  pull_request:
    branches:
      - develop
      - "feature/was9_common"
#  workflow_call:
#    inputs:
#      environment:
#        required: true
#        type: string
#      buildNumber:
#        required: true
#        type: string
#
#  workflow_dispatch:
#    inputs:
#      environment:
#        description: "Deployment environment"
#        required: true
#        type: choice
#        options:
#          - uat92
#          - uat93
#          - prod
#      buildNumber:
#        description: "Build number or tag to deploy"
#        required: true
#        type: string

jobs:
  prepare-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up deployment variables
        run: |
          echo "Preparing deployment for environment: ${{ inputs.environment }} with build number: ${{ inputs.buildNumber }}"
          echo "ENVIRONMENT=${{ inputs.environment }}" >> "$GITHUB_ENV"
          echo "BUILD_NUMBER=${{ inputs.buildNumber }}" >> "$GITHUB_ENV"
