name: CI

on:
  pull_request:
    branches:
      - master
      - develop
      - "feature/was9_common"
      - "feature/pre-production"
  push:
    branches:
      - master
      - develop
      - "feature/was9_common"
      - "feature/pre-production"
    tags:
      - "v*.*.*"
jobs:
  build:
    name: Lint, Build & Test
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.metadata.outputs.build_number }}
      environment: ${{ steps.metadata.outputs.environment }}
      should_deploy: ${{ steps.metadata.outputs.should_deploy }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Metadata Info
        id: metadata
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "build_number=uat92-${GITHUB_SHA::7}-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_OUTPUT
            echo "environment=uat92" >> $GITHUB_OUTPUT
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          
          elif [[ "${{ github.ref }}" == "refs/heads/feature/was9_common" ]]; then
            echo "build_number=uat93-was9common-${GITHUB_SHA::7}-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_OUTPUT
            echo "environment=uat93-was9common" >> $GITHUB_OUTPUT
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "build_number=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "environment=prod" >> $GITHUB_OUTPUT
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          
          else
            echo "build_number=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
            echo "environment=none" >> $GITHUB_OUTPUT
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Build war
        run: echo "build war success"

      - name: build docker
        run: echo "build docker success"

  trigger-cd-uat92:
    needs: build
    if: needs.build.outputs.should_deploy == 'true' && needs.build.outputs.environment == 'uat92'
    uses: ./.github/workflows/cd.yml
    with:
      environment: uat92
      buildNumber: ${{ needs.build.outputs.build_number }}
    secrets: inherit

  trigger-cd-uat93-was9common:
    needs: build
    if: needs.build.outputs.should_deploy == 'true' && needs.build.outputs.environment == 'uat93-was9common'
    uses: ./.github/workflows/cd.yml
    with:
      environment: uat93
      buildNumber: ${{ needs.build.outputs.build_number }}
    secrets: inherit
